var formatSourceData = function (args) {
  var sourceData = {};
  var argKeys = Object.keys(args);
  var valueParts;
  for (var i = 0; i < argKeys.length; i++) {
    var key = argKeys[i];
    var value = args[key];
    if (typeof value === 'string' && value.indexOf(';;') !== -1 && value.indexOf('::') !== -1) {
      sourceData[key] = {};
      valueParts = value.split(';;');
      for (var j = 0; j < valueParts.length - 1; j++) {
        var keyValParts = valueParts[j].split('::');
        if (sourceData[key][keyValParts[0]]) {
          if (!Array.isArray(sourceData[key][keyValParts[0]])) {
            var currentValue = sourceData[key][keyValParts[0]];
            sourceData[key][keyValParts[0]] = [];
            sourceData[key][keyValParts[0]].push(currentValue);
          }
          sourceData[key][keyValParts[0]].push(keyValParts[1] === '' ? null : keyValParts[1]);
        } else {
          sourceData[key][keyValParts[0]] = keyValParts[1] === '' ? null : keyValParts[1];
        }

      }
    } else if (typeof value === 'string' && value.indexOf(';;') !== -1) {
      if (value.substr(value.length - 2) === ';;') {
        value = value.slice(0, value.length - 2);
      }
      sourceData[key] = value.split(';;');
    } else if (typeof value === 'string' && value.indexOf('::') !== -1) {
      valueParts = value.split('::');
      sourceData[key] = {};
      sourceData[key][valueParts[0]] = valueParts[1];
    } else {
      sourceData[key] = value;
    }
  }
  return sourceData;
};
returnObj = {
  sourceData: formatSourceData(args),
  vendorRequestBody: {
    'id': null,
    'name': null,
    'code': null,
    'description': null,
    'status': null,
    'language': null,
    'isVendor': null,
    'sanCode': null,
    'aliases': [],
    'addresses': [],
    'phoneNumbers': [],
    'emails': [],
    'urls': [],
    'contacts': [],
    'agreements': [],
    'vendorCurrencies': [],
    'claimingInterval': null,
    'interfaces': [],
    'accounts': [],
    'changelogs': []
  },
  statuses: [
    'Active',
    'Inactive',
    'Pending'
  ],
  categories: {
    ORDER: '9718aa38-8fb4-49e4-910b-bbdc2b1aa579',
    PAYMENT: 'ac6528cc-8ba0-4678-9b08-627ca2314ffd',
    CLAIM: 'd931bdc4-ef47-4871-98d7-2c48f5ff4fe0',
    RETURN: '544459af-fc5e-4e64-9b40-acb84ac4d3aa',
    OTHER: '04f39c67-b212-4fe7-87f0-0875c8995d21'
  },
  vendorTypes: {
    'BF': 'Backfile vendor',
    'CO': 'Continuations vendor',
    'DB': 'Database vendor',
    'ER': 'Electronic resources vendor',
    'MO': 'Monographs vendor',
    'NO': 'Converted from NOTIS to Voyager',
    'SR': 'Serials vendor'
  },
  phoneTypes: {
    '1': 'Mobile',
    '2': 'Fax',
    '3': 'Other'
  },
  countryCodes: {
    'AFGHANISTAN': 'AFG',
    'ALA ALAND ISLANDS': 'ALA',
    'ALBANIA': 'ALB',
    'ALGERIA': 'DZA',
    'AMERICAN SAMOA': 'ASM',
    'ANDORRA': 'AND',
    'ANGOLA': 'AGO',
    'ANGUILLA': 'AIA',
    'ANTARCTICA': 'ATA',
    'ANTIGUA AND BARBUDA': 'ATG',
    'ARGENTINA': 'ARG',
    'ARMENIA': 'ARM',
    'ARUBA': 'ABW',
    'AUSTRALIA': 'AUS',
    'AUSTRIA': 'AUT',
    'AZERBAIJAN': 'AZE',
    'BAHAMAS': 'BHS',
    'BAHRAIN': 'BHR',
    'BANGLADESH': 'BGD',
    'BARBADOS': 'BRB',
    'BELARUS': 'BLR',
    'BELGIUM': 'BEL',
    'BELIZE': 'BLZ',
    'BENIN': 'BEN',
    'BERMUDA': 'BMU',
    'BHUTAN': 'BTN',
    'BOLIVIA': 'BOL',
    'BOSNIA AND HERZEGOVINA': 'BIH',
    'BOTSWANA': 'BWA',
    'BOUVET ISLAND': 'BVT',
    'BRAZIL': 'BRA',
    'BRITISH VIRGIN ISLANDS': 'VGB',
    'BRITISH INDIAN OCEAN TERRITORY': 'IOT',
    'BRUNEI DARUSSALAM': 'BRN',
    'BULGARIA': 'BGR',
    'BURKINA FASO': 'BFA',
    'BURUNDI': 'BDI',
    'CAMBODIA': 'KHM',
    'CAMEROON': 'CMR',
    'CANADA': 'CAN',
    'CAPE VERDE': 'CPV',
    'CAYMAN ISLANDS': 'CYM',
    'CENTRAL AFRICAN REPUBLIC': 'CAF',
    'CHAD': 'TCD',
    'CHILE': 'CHL',
    'CHINA': 'CHN',
    'HONG KONG': 'HKG',
    'MACAO': 'MAC',
    'CHRISTMAS ISLAND': 'CXR',
    'COCOS (KEELING) ISLANDS': 'CCK',
    'COLOMBIA': 'COL',
    'COMOROS': 'COM',
    'CONGO (BRAZZAVILLE)': 'COG',
    'CONGO': 'COD',
    'COOK ISLANDS': 'COK',
    'COSTA RICA': 'CRI',
    'CROATIA': 'HRV',
    'CUBA': 'CUB',
    'CYPRUS': 'CYP',
    'CZECH REPUBLIC': 'CZE',
    'DENMARK': 'DNK',
    'DJIBOUTI': 'DJI',
    'DOMINICA': 'DMA',
    'DOMINICAN REPUBLIC': 'DOM',
    'ECUADOR': 'ECU',
    'EGYPT': 'EGY',
    'EL SALVADOR': 'SLV',
    'ENGLAND': 'GBR',
    'EQUATORIAL GUINEA': 'GNQ',
    'ERITREA': 'ERI',
    'ESPANA': 'ESP',
    'ESTONIA': 'EST',
    'ETHIOPIA': 'ETH',
    'FALKLAND ISLANDS (MALVINAS)': 'FLK',
    'FAROE ISLANDS': 'FRO',
    'FIJI': 'FJI',
    'FINLAND': 'FIN',
    'FRANCE': 'FRA',
    'FRENCH GUIANA': 'GUF',
    'FRENCH POLYNESIA': 'PYF',
    'FRENCH SOUTHERN TERRITORIES': 'ATF',
    'GABON': 'GAB',
    'GAMBIA': 'GMB',
    'GEORGIA': 'GEO',
    'GERMANY': 'DEU',
    'GHANA': 'GHA',
    'GIBRALTAR': 'GIB',
    'GREAT BRITAIN': 'GBR',
    'GREECE': 'GRC',
    'GREENLAND': 'GRL',
    'GRENADA': 'GRD',
    'GUADELOUPE': 'GLP',
    'GUAM': 'GUM',
    'GUATEMALA': 'GTM',
    'GUERNSEY': 'GGY',
    'GUINEA': 'GIN',
    'GUINEA-BISSAU': 'GNB',
    'GUYANA': 'GUY',
    'HAITI': 'HTI',
    'HEARD AND MCDONALD ISLANDS': 'HMD',
    'HOLY SEE (VATICAN CITY STATE)': 'VAT',
    'HONDURAS': 'HND',
    'HUNGARY': 'HUN',
    'ICELAND': 'ISL',
    'INDIA': 'IND',
    'INDONESIA': 'IDN',
    'IRAN': 'IRN',
    'IRAQ': 'IRQ',
    'IRELAND': 'IRL',
    'ISLE OF MAN': 'IMN',
    'ISRAEL': 'ISR',
    'ITALY': 'ITA',
    'JAMAICA': 'JAM',
    'JAPAN': 'JPN',
    'JERSEY': 'JEY',
    'JORDAN': 'JOR',
    'KAZAKHSTAN': 'KAZ',
    'KENYA': 'KEN',
    'KIRIBATI': 'KIR',
    'KOREA (NORTH)': 'PRK',
    'KOREA': 'KOR',
    'S. KOREA': 'KOR',
    'KUWAIT': 'KWT',
    'KYRGYZSTAN': 'KGZ',
    'LAO PDR': 'LAO',
    'LATVIA': 'LVA',
    'LEBANON': 'LBN',
    'LESOTHO': 'LSO',
    'LIBERIA': 'LBR',
    'LIBYA': 'LBY',
    'LIECHTENSTEIN': 'LIE',
    'LITHUANIA': 'LTU',
    'LUXEMBOURG': 'LUX',
    'MACEDONIA': 'MKD',
    'MADAGASCAR': 'MDG',
    'MALAWI': 'MWI',
    'MALAYSIA': 'MYS',
    'MALDIVES': 'MDV',
    'MALI': 'MLI',
    'MALTA': 'MLT',
    'MARSHALL ISLANDS': 'MHL',
    'MARTINIQUE': 'MTQ',
    'MAURITANIA': 'MRT',
    'MAURITIUS': 'MUS',
    'MAYOTTE': 'MYT',
    'MEXICO': 'MEX',
    'MICRONESIA': 'FSM',
    'MOLDOVA': 'MDA',
    'MONACO': 'MCO',
    'MONGOLIA': 'MNG',
    'MONTENEGRO': 'MNE',
    'MONTSERRAT': 'MSR',
    'MOROCCO': 'MAR',
    'MOZAMBIQUE': 'MOZ',
    'MYANMAR': 'MMR',
    'NAMIBIA': 'NAM',
    'NAURU': 'NRU',
    'NEPAL': 'NPL',
    'NETHERLANDS': 'NLD',
    'NETHERLANDS ANTILLES': 'ANT',
    'NEW CALEDONIA': 'NCL',
    'NEW ZEALAND': 'NZL',
    'NICARAGUA': 'NIC',
    'NIGER': 'NER',
    'NIGERIA': 'NGA',
    'NIUE': 'NIU',
    'NORFOLK ISLAND': 'NFK',
    'NORTHERN IRELAND': 'GBR',
    'NORTHERN MARIANA ISLANDS': 'MNP',
    'NORWAY': 'NOR',
    'OMAN': 'OMN',
    'PAKISTAN': 'PAK',
    'PALAU': 'PLW',
    'PALESTINIAN TERRITORY': 'PSE',
    'PANAMA': 'PAN',
    'PAPUA NEW GUINEA': 'PNG',
    'PARAGUAY': 'PRY',
    'PERU': 'PER',
    'PHILIPPINES': 'PHL',
    'PITCAIRN': 'PCN',
    'POLAND': 'POL',
    'PORTUGAL': 'PRT',
    'PUERTO RICO': 'PRI',
    'QATAR': 'QAT',
    'REPUBLIC OF KOREA': 'KOR',
    'ROMANIA': 'ROU',
    'RUSSIA': 'RUS',
    'RUSSIAN FEDERATION': 'RUS',
    'RWANDA': 'RWA',
    'SAINT HELENA': 'SHN',
    'SAINT KITTS AND NEVIS': 'KNA',
    'SAINT LUCIA': 'LCA',
    'SAINT-MARTIN (FRENCH PART)': 'MAF',
    'SAINT PIERRE AND MIQUELON': 'SPM',
    'SAINT VINCENT AND GRENADINES': 'VCT',
    'SAMOA': 'WSM',
    'SAN MARINO': 'SMR',
    'SAO TOME AND PRINCIPE': 'STP',
    'SAUDI ARABIA': 'SAU',
    'SCOTLAND': 'GBR',
    'SENEGAL': 'SEN',
    'SERBIA': 'SRB',
    'SEYCHELLES': 'SYC',
    'SIERRA LEONE': 'SLE',
    'SINGAPORE': 'SGP',
    'SLOVAKIA': 'SVK',
    'SLOVENIA': 'SVN',
    'SOLOMON ISLANDS': 'SLB',
    'SOMALIA': 'SOM',
    'SOUTH AFRICA': 'ZAF',
    'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS': 'SGS',
    'SOUTH SUDAN': 'SSD',
    'SPAIN': 'ESP',
    'SRI LANKA': 'LKA',
    'SUDAN': 'SDN',
    'SURINAME': 'SUR',
    'SVALBARD AND JAN MAYEN ISLANDS': 'SJM',
    'SWAZILAND': 'SWZ',
    'SWEDEN': 'SWE',
    'SWITZERLAND': 'CHE',
    'SYRIA': 'SYR',
    'TAIWAN': 'TWN',
    'TAJIKISTAN': 'TJK',
    'TANZANIA': 'TZA',
    'THAILAND': 'THA',
    'THE NETHERLANDS': 'NLD',
    'TIMOR-LESTE': 'TLS',
    'TOGO': 'TGO',
    'TOKELAU': 'TKL',
    'TONGA': 'TON',
    'TRINIDAD AND TOBAGO': 'TTO',
    'TRINIDAD & TOBAGO': 'TTO',
    'TUNISIA': 'TUN',
    'TURKEY': 'TUR',
    'TURKMENISTAN': 'TKM',
    'TURKS AND CAICOS ISLANDS': 'TCA',
    'TUVALU': 'TUV',
    'UAE': 'UAE',
    'UGANDA': 'UGA',
    'UKRAINE': 'UKR',
    'UNITED ARAB EMIRATES': 'ARE',
    'U.A.E.': 'ARE',
    'U.K.': 'GBR',
    'UK': 'GBR',
    'UNITED KINGDOM': 'GBR',
    'US': 'USA',
    'U.S.A.': 'USA',
    'USA': 'USA',
    'UNITED STATES': 'USA',
    'URUGUAY': 'URY',
    'UZBEKISTAN': 'UZB',
    'VANUATU': 'VUT',
    'VENEZUELA': 'VEN',
    'VIET NAM': 'VNM',
    'VIRGIN ISLANDS': 'VIR',
    'WALES': 'GBR',
    'WALLIS AND FUTUNA ISLANDS': 'WLF',
    'WESTERN SAHARA': 'ESH',
    'YEMEN': 'YEM',
    'ZAMBIA': 'ZMB',
    'ZIMBABWE': 'ZWE'
  }
};